#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — the parts of bringing this site up that only a human can do.
# Everything else (build, checks, upload) is .github/workflows/deploy.yml.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# The origin the site names in its own canonical links, read from the one place
# that owns it, so this wizard cannot walk you through setting up a domain the
# built pages do not claim to live on.
ORIGIN=$(node -p "require('node:fs').readFileSync('src/lib/site.ts','utf8').match(/SITE_ORIGIN = '([^']+)'/)[1]")
DOMAIN=${ORIGIN#https://}

banner "Gender Diary landing site on lh.pl"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Give $DOMAIN a directory on the account"
say "The account holds several unrelated sites, each in its own directory, and"
say "the panel is what decides which directory a domain serves. A DNS record"
say "alone does not do it: until the mapping exists the domain answers with"
say "somebody else's site or with nothing at all."
open_url "https://panel.lh.pl/"
step "Log in, then Domains -> add $DOMAIN, or open it if it is already listed."
step "Let the panel create its directory, or point it at an empty one."
step "Issue the TLS certificate for it in the panel's SSL section."
warn "The certificate is not optional. The site is HTTPS only, and the account's"
warn "existing certificate covers *.lh.pl rather than this domain."
pause "Done, and the certificate names $DOMAIN?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The deploy target, as the FTP account sees it"
say "This is the one value worth being slow about. The upload mirrors into this"
say "directory, so a wrong answer writes this site over a neighbouring one."
say ""
say "Two views of the same account disagree, which is the trap: over SFTP the"
say "directories sit under public_html/, and over FTP - which is what the"
say "deploy uses - the same directory is named without that prefix. The live"
say "deploy for nazwozbior.pl uses a bare 'imiona.rejewska.pl/', so on this"
say "account the FTP session starts inside public_html."
note "Read the panel's directory for $DOMAIN, drop any public_html/ prefix, and"
note "add a trailing slash. Likely '$DOMAIN/'."
ask FTP_SERVER_DIR "Deploy target:"
while [[ -z "$FTP_SERVER_DIR" || "$FTP_SERVER_DIR" != */ || "$FTP_SERVER_DIR" == "public_html/" ]]; do
  warn "It has to name a single site's directory and end in a slash."
  ask FTP_SERVER_DIR "Deploy target:"
done
write_env FTP_SERVER_DIR "$FTP_SERVER_DIR"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Check the DNS actually resolves"
say "Reading it rather than trusting it: $DOMAIN has to resolve to the lh.pl"
say "address before anything else here is worth testing."
if command -v dig >/dev/null 2>&1; then
  RESOLVED=$(dig +short "$DOMAIN" | tail -n1)
else
  RESOLVED=$(getent hosts "$DOMAIN" | awk '{print $1}' | tail -n1)
fi
if [[ -n "$RESOLVED" ]]; then
  say "$DOMAIN resolves to $RESOLVED"
  note "Compare that with the hosting address in the panel. A wildcard record on"
  note "the parent domain will answer here too, which looks the same and is not."
else
  warn "$DOMAIN does not resolve yet."
  step "At the registrar or DNS provider for barankiewicz.dev, add the record"
  step "  the lh.pl panel names for this account, then wait for it to spread."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Credentials for the deploy"
say "These go to GitHub Actions and nowhere else. They open this hosting"
say "account only. The Journal lives on a different host with its own"
say "credentials, and nothing here can reach it."
note "The account's host and username are in the lhpl-managed-hosting skill, and"
note "the wallet is keyed on both, so a typo here turns into a password prompt."
ask FTP_SERVER "FTP host (e.g. serwerNNNNNN.lh.pl):"
ask FTP_USERNAME "FTP username:"
write_env FTP_SERVER "$FTP_SERVER"
write_env FTP_USERNAME "$FTP_USERNAME"

FTP_PASSWORD=""
if command -v secret-tool >/dev/null 2>&1; then
  FTP_PASSWORD=$(secret-tool lookup service lhpl host "$FTP_SERVER" username "$FTP_USERNAME" || true)
fi
if [[ -n "$FTP_PASSWORD" ]]; then
  say "Password found in the wallet."
else
  warn "Nothing in the wallet under $FTP_USERNAME at $FTP_SERVER."
  warn "Check those two before typing a password: the wallet already has one."
  ask_secret FTP_PASSWORD "Account password:"
  if command -v secret-tool >/dev/null 2>&1 && confirm "Store it in the wallet for next time?"; then
    printf '%s' "$FTP_PASSWORD" |
      secret-tool store --label="lh.pl hosting ($FTP_USERNAME)" \
        service lhpl host "$FTP_SERVER" username "$FTP_USERNAME"
  fi
fi
warn "The password is never written to a file in this repository. The wallet and"
warn "the GitHub secret are the only two places it lives."

set_secret FTP_SERVER "$FTP_SERVER"
set_secret FTP_USERNAME "$FTP_USERNAME"
set_secret FTP_PASSWORD "$FTP_PASSWORD"
set_var FTP_SERVER_DIR "$FTP_SERVER_DIR"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Deploy, then read the live response"
say "The workflow builds with SITE_ENV=production and uploads build/ over FTPS."
say "Nothing about the headers or the crawl policy is settled until it has been"
say "read off the live site, which is what this stage does."
if confirm "Run the deploy workflow on main now?"; then
  gh workflow run deploy.yml --ref main || warn "gh could not start it; push to main instead."
  say "Watch it with: gh run watch"
fi
pause "Press Enter once the deploy has finished."

say ""
say "Response headers:"
curl -sSI "https://$DOMAIN/" | grep -iE '^(HTTP|content-security-policy|referrer-policy)' || true
say ""
say "Content policy carried by the page itself:"
curl -sS "https://$DOMAIN/en/" | grep -o '<meta http-equiv="content-security-policy"[^>]*>' || true
say ""
say "Crawl policy - a preview build names itself here:"
curl -sS "https://$DOMAIN/robots.txt" || true
say ""
warn "Read those before ticking anything in the ticket:"
note "  - a Referrer-Policy header, or the meta element if mod_headers is off"
note "  - a content policy with default-src 'none' in it"
note "  - robots.txt naming a sitemap, not calling itself a preview build"

finish
